apiVersion: apps/v1
kind: Deployment
metadata:
  name: allouchi-deployment
  labels:
    app: allouchi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: allouchi
  template:
    metadata:
      labels:
        app: allouchi
    spec:
      containers:
      - name: allouchi
        image: lobnasellami/jenkins-pipeline:latest
        ports:
        - containerPort: 80
